'use strict';
(async () => {
const A=AtlasFeedback,$=id=>document.getElementById(id);let offset=0,total=0,objects=[],current=null,base=null,activePatch={},busy=false,selection=0;
const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value??'—';if(cls)e.className=cls;return e;};
function status(value,error=false){$('admin-status').textContent=value;$('admin-status').classList.toggle('error',error);}
function reset(){selection++;current=null;base=null;objects=[];$('review').replaceChildren(text('p','Ընտրեք հաղորդումը։'));$('queue').replaceChildren();$('admin-panel').hidden=true;$('login-section').hidden=false;}
async function enter(){try{if(!await A.rpc('is_feedback_admin',{},true)){await A.signOut();reset();throw Error('Այս հաշիվը հաղորդումները կառավարելու իրավունք չունի։');}$('account').textContent=A.getSession()?.user?.email||'Պատասխանատու';$('login-section').hidden=true;$('admin-panel').hidden=false;objects=await A.loadObjects();await queue();status('');}catch(e){reset();status(A.showError(e),true);}}
$('login-form').onsubmit=async e=>{e.preventDefault();$('login-button').disabled=true;try{await A.signIn($('email').value.trim(),$('password').value);$('password').value='';await enter();}catch(e){status(A.showError(e),true);}finally{$('login-button').disabled=false;}};
$('logout').onclick=async()=>{try{await A.signOut();}catch{}reset();status('Դուք դուրս եք եկել։');};
async function queue(){const token=selection;const result=await A.rpc('list_feedback_reports',{p_status:$('filter').value,p_offset:offset},true);if(token!==selection)return;total=result.total;$('queue-count').textContent=total+' հաղորդում';$('queue').replaceChildren();for(const r of result.rows){const b=text('button','#'+r.report_number+' · '+(r.object_name||A.TYPES[r.object_type]||'Հաղորդում')+'\n'+(r.settlement||'')+' · '+A.STATUSES[r.status]);b.type='button';b.onclick=()=>open(r.id);$('queue').append(b);}if(!result.rows.length)$('queue').append(text('p','Այս բաժնում հաղորդումներ չկան։'));$('prev').disabled=offset===0;$('next').disabled=offset+30>=total;}
for(const [id,change] of [['prev',-30],['next',30]])$(id).onclick=async()=>{offset=Math.max(0,offset+change);try{await queue();}catch(e){status(A.showError(e),true);}};
$('filter').onchange=async()=>{offset=0;try{await queue();}catch(e){status(A.showError(e),true);}};
$('refresh').onclick=async()=>{try{objects=await A.loadObjects();await queue();if(current)await open(current.id);}catch(e){status(A.showError(e),true);}};
function labelInput(container,label,id,value,type='text'){const l=text('label',label),input=document.createElement(type==='textarea'?'textarea':'input');input.id=id;if(type!=='textarea')input.type=type;input.value=value??'';l.append(input);container.append(l);return input;}
function objectLink(id){const a=text('a','Բացել Ատլասում՝ #'+id);a.href='index.html?id='+encodeURIComponent(id);a.target='_blank';a.rel='noopener';return a;}
async function open(id){if(busy)return;const token=++selection;status('Բեռնվում է…');try{const r=await A.rpc('get_feedback_report',{p_id:id},true);if(token!==selection)return;current=r;base=null;render();status('');loadPhotos(r,token);if(r.payload.related_object_id)await chooseObject(r.payload.related_object_id,token);}catch(e){status(A.showError(e),true);}}
function render(){const r=current,p=r.payload,root=$('review');root.replaceChildren(text('h2','Հաղորդում #'+r.report_number),text('p',A.STATUSES[r.status]+' · '+new Date(r.created_at).toLocaleString('hy-AM'),'help'),text('pre',A.preparedMessage(p),'preview'));
root.append(text('h3','Հայտնողի տվյալները'),text('p',(p.reporter_name||'Անունը նշված չէ')+' · '+p.reporter_phone),text('p',p.location_source==='gps'?'Հեռախոսի տեղադրություն, ճշտություն՝ '+Math.round(p.accuracy_m||0)+' մ':'Կետի աղբյուրը՝ '+({manual:'Ձեռքով',map:'Քարտեզ',existing:'Ատլասի առկա կետ'}[p.location_source]||'—'),'help'));
if(A.coordinates(p.latitude,p.longitude)){const a=text('a','Դիտել հաղորդված կետը քարտեզում');a.href='https://www.openstreetmap.org/?mlat='+p.latitude+'&mlon='+p.longitude+'#map=16/'+p.latitude+'/'+p.longitude;a.target='_blank';a.rel='noopener';root.append(a);}
if(p.related_object_id)root.append(text('p','Հայտնողի ընտրած Ատլասի գրառումը՝ #'+p.related_object_id));
root.append(text('h3','Լուսանկարներ'));const photos=document.createElement('div');photos.id='review-photos';photos.className='photos';photos.append(text('p','Լուսանկարները բեռնվում են…','help'));root.append(photos);
if(r.events?.length){root.append(text('h3','Որոշումների պատմություն'));for(const e of r.events)root.append(text('p',new Date(e.created_at).toLocaleString('hy-AM')+' · '+e.action+' · '+(e.note||''),'help'));}
if(['accepted','rejected'].includes(r.status)){if(r.resolved_object_id)root.append(objectLink(r.resolved_object_id));root.append(text('p','Այս հաղորդման վերաբերյալ վերջնական որոշումն արդեն պահպանված է։'));return;}
root.append(text('h3','Գործողությունը Ատլասում'));const l=text('label','Հաստատելիս՝'),mode=document.createElement('select');mode.id='mode';for(const [value,title] of [['create','Ստեղծել նոր օբյեկտ'],['update','Ուղղել առկա օբյեկտը'],['accept','Ընդունել՝ առանց Ատլասի գրառումը փոխելու']]){const o=text('option',title);o.value=value;mode.append(o);}mode.value=p.kind==='new'&&p.object_type!=='other'?'create':p.kind==='general'||p.object_type==='other'?'accept':'update';l.append(mode);root.append(l);
const target=document.createElement('div');target.id='target-wrap';labelInput(target,'Փնտրեք փոփոխվող օբյեկտը','target-search','');const results=document.createElement('div');results.id='target-results';target.append(results);const chosen=text('p','Ընտրեք Ատլասի առկա գրառումը։','help');chosen.id='target-label';target.append(chosen);root.append(target);
$('target-search').oninput=()=>{results.replaceChildren();const q=$('target-search').value.trim().toLocaleLowerCase();if(!q)return;for(const o of objects.filter(o=>(o.name_hy||'').toLocaleLowerCase().includes(q)||String(o.id)===q).slice(0,15)){const b=text('button',(o.name_hy||'Առանց անվան')+' · '+(A.TYPES[o.type]||o.type)+' · #'+o.id);b.type='button';b.onclick=()=>chooseObject(o.id,selection);results.append(b);}};
const editor=document.createElement('div');editor.id='editor';root.append(editor);root.append(text('h3','Փոփոխության նախադիտում'));const preview=document.createElement('div');preview.id='change-preview';root.append(preview);
labelInput(root,'Ստուգողի նշումը (մերժման կամ ճշտման համար պարտադիր)','review-note',r.review_note||'','textarea').maxLength=2000;
const actions=document.createElement('div');actions.className='actions';for(const [id,title,action] of [['approve','Հաստատել նախադիտված փոփոխությունը','approve'],['clarify','Պահանջել ճշտում','needs_details'],['reject','Մերժել','reject']]){const b=text('button',title,id==='approve'?'primary':'');b.type='button';b.id=id;b.onclick=()=>decision(action);actions.append(b);}root.append(actions,text('p','«Պահանջել ճշտում»-ը պահպանում է կարգավիճակն ու ձեր նշումը։ Հայտնողի հետ կապվեք նշված հեռախոսով։ Ավտոմատ SMS չի ուղարկվում։','help'));
mode.onchange=buildEditor;buildEditor();}
async function chooseObject(id,token){try{const selected=await A.rpc('get_feedback_object',{p_id:Number(id)},true);if(token!==selection)return;base=selected;if(!$('mode')||$('mode').value!=='update')return;$('target-label').textContent='Փոփոխվում է՝ '+(base.name_hy||'')+' · #'+base.id;$('target-results').replaceChildren();buildEditor();}catch(e){status(A.showError(e),true);}}
function buildEditor(){const mode=$('mode').value,p=current.payload,root=$('editor');root.replaceChildren();$('target-wrap').hidden=mode!=='update';if(mode==='accept'){previewChanges();return;}if(mode==='update'&&!base){root.append(text('p','Նախ ընտրեք փոփոխվող օբյեկտը։'));previewChanges();return;}
const grid=document.createElement('div');grid.className='form-grid';root.append(grid);
if(mode==='create'){const l=text('label','Ատլասի օբյեկտի տեսակը'),select=document.createElement('select');select.id='edit-type';for(const [key,value] of Object.entries(A.TYPES)){if(key==='other')continue;const o=text('option',value);o.value=key;select.append(o);}select.value=p.object_type==='other'?'spring':p.object_type;l.append(select);grid.append(l);select.onchange=()=>{$('edit-status').value=['reservoir','canal','hydropower'].includes(select.value)?'operational':'natural';previewChanges();};
const sl=text('label','Կարգավիճակ'),ss=document.createElement('select');ss.id='edit-status';for(const [key,value] of Object.entries({natural:'Բնական',operational:'Գործող',planned:'Նախատեսվող',construction:'Կառուցվող',industrial:'Արդյունաբերական'})){const o=text('option',value);o.value=key;ss.append(o);}ss.value=['reservoir','canal','hydropower'].includes(select.value)?'operational':'natural';ss.onchange=previewChanges;sl.append(ss);grid.append(sl);}
const values=mode==='create'?{name_hy:p.object_name||p.local_name||'',province:'',description_hy:p.description,latitude:p.latitude,longitude:p.longitude}:base;
for(const key of ['name_hy','province','description_hy','latitude','longitude']){const wrap=document.createElement('div');if(key==='description_hy')wrap.className='wide';if(mode==='update'){const label=text('label','Փոխել՝ '+A.FIELDS[key],'check-label'),check=document.createElement('input');check.type='checkbox';check.id='use-'+key;label.prepend(check);wrap.append(label);check.onchange=()=>{if(['latitude','longitude'].includes(key)){const other=key==='latitude'?'longitude':'latitude';$('use-'+other).checked=check.checked;$('edit-'+other).disabled=!check.checked;}$('edit-'+key).disabled=!check.checked;previewChanges();};}
const input=labelInput(wrap,A.FIELDS[key],'edit-'+key,values[key],key==='description_hy'?'textarea':['latitude','longitude'].includes(key)?'number':'text');if(input.type==='number')input.step='any';input.disabled=mode==='update';input.oninput=previewChanges;grid.append(wrap);}
if(mode==='update'){root.append(text('p','Ընտրեք միայն այն դաշտերը, որոնք ուզում եք փոխել։ Հաղորդված նկարագրությունը չի փոխարինում առկա նկարագրությունն ինքնաբերաբար։','help'));const b=text('button','Կիրառել հաղորդված կոորդինատները');b.type='button';b.onclick=()=>{if(!A.coordinates(p.latitude,p.longitude))return;for(const key of ['latitude','longitude']){$('edit-'+key).value=p[key];$('use-'+key).checked=true;$('edit-'+key).disabled=false;}previewChanges();};root.append(b);if(base.geometry&&base.geometry.type!=='Point'){for(const k of ['latitude','longitude']){$('use-'+k).disabled=true;$('edit-'+k).disabled=true;}b.disabled=true;root.append(text('p','Օբյեկտն ունի գծային կամ տարածքային քարտեզային ձև։ Այս էջից կարող եք փոխել անվանումն ու նկարագրությունը։ Կետի փոփոխությունը պահանջում է առանձին քարտեզագրական ստուգում։','notice'));}}
previewChanges();}
function patch(){const mode=$('mode').value;if(mode==='accept'||(mode==='update'&&!base))return {};const result={};if(mode==='create'){result.type=$('edit-type').value;result.status=$('edit-status').value;}for(const key of ['name_hy','province','description_hy','latitude','longitude']){if(mode==='update'&&!$('use-'+key)?.checked)continue;const value=$('edit-'+key).value;result[key]=['latitude','longitude'].includes(key)?value===''?null:Number(value):value.trim()||null;}return result;}
function previewChanges(){activePatch=patch();const root=$('change-preview');root.replaceChildren();const mode=$('mode').value;if(mode==='accept'){root.append(text('p','Հաղորդումը կընդունվի։ Ատլասի օբյեկտների տվյալները չեն փոխվի։'));$('approve').disabled=false;return;}const changes=A.diff(mode==='create'?{}:base,activePatch);if(!changes.length)root.append(text('p','Փոփոխություն ընտրված չէ։'));else{const table=document.createElement('table');table.className='diff-table';const head=document.createElement('tr');for(const label of ['Դաշտ','Առկա արժեք','Հաստատումից հետո'])head.append(text('th',label));table.append(head);for(const c of changes){const tr=document.createElement('tr');tr.append(text('td',c.label),text('td',c.before),text('td',c.after));table.append(tr);}root.append(table);}$('approve').disabled=!changes.length||(mode==='update'&&!base);}
async function decision(action){if(busy)return;const mode=$('mode').value,p=action==='approve'?patch():{},actual=action==='approve'?mode:action,note=$('review-note').value.trim();if(['reject','needs_details'].includes(actual)&&note.length<3){status('Նշեք որոշման պատճառը։',true);return;}if(['create','update'].includes(actual)){if(actual==='update'&&!base){status('Ընտրեք փոփոխվող օբյեկտը։',true);return;}if('name_hy'in p&&!p.name_hy){status('Լրացրեք օբյեկտի անունը։',true);return;}if(actual==='create'||'latitude'in p){if(!A.coordinates(p.latitude,p.longitude)){status('Լրացրեք վավեր կոորդինատներ։',true);return;}}}busy=true;for(const b of $('review').querySelectorAll('button,input,select,textarea'))b.disabled=true;status('Որոշումը պահպանվում է…');try{const result=await A.rpc('review_feedback_report',{p_id:current.id,p_revision:current.revision,p_action:actual,p_patch:p,p_target_id:actual==='update'?base.id:null,p_expected_object:actual==='update'?base:null,p_note:note},true);busy=false;const id=current.id;objects=await A.loadObjects();await queue();await open(id);status(result.object_id?'Որոշումն ու Ատլասի գրառումը պահպանված են։ Օբյեկտ՝ #'+result.object_id:'Որոշումը պահպանված է։');}catch(e){busy=false;status(A.showError(e),true);render();loadPhotos(current,selection);}finally{busy=false;}}
async function loadPhotos(r,token){try{const prefix=r.id+'/'+r.upload_token+'/';const rows=await A.fetchJSON('/storage/v1/object/list/feedback-photos',{method:'POST',body:{prefix,limit:5,offset:0,sortBy:{column:'name',order:'asc'}}},true);if(token!==selection)return;const root=$('review-photos');root.replaceChildren();if(!rows.length){root.append(text('p','Լուսանկարներ չեն փոխանցվել։','help'));return;}for(const row of rows){const value=await A.fetchJSON('/storage/v1/object/sign/feedback-photos/'+prefix+row.name,{method:'POST',body:{expiresIn:300}},true);if(token!==selection)return;const signed=value.signedURL||value.signedUrl;const a=document.createElement('a');a.href=signed.startsWith('http')?signed:A.URL+'/storage/v1'+signed;a.target='_blank';a.rel='noopener';const img=document.createElement('img');img.src=a.href;img.alt='Հաղորդում #'+r.report_number+'՝ կցված լուսանկար';a.append(img);root.append(a);}root.append(text('p','Լուսանկարները մասնավոր են։ Հղումները գործում են 5 րոպե։','help'));}catch(e){if(token===selection&&$('review-photos'))$('review-photos').replaceChildren(text('p','Լուսանկարները չբեռնվեցին։ '+A.showError(e),'error'));}}
if(A.getSession())await enter();
})();
